import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { openclawTarget } from "../src/targets/openclaw.js";
import type { PersonaManifest, LoadedSkill } from "../src/types/index.js";

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "spm-openclaw-test-"));
});

afterEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true });
});

function testPersona(overrides: Partial<PersonaManifest> = {}): PersonaManifest {
  return {
    schema_version: 1,
    name: "test-agent",
    version: "1.2.0",
    description: "A test persona",
    author: "tester",
    license: "MIT",
    character: {
      role: "Senior backend engineer specializing in distributed systems.",
      tone: "direct, concise",
      guidelines: [
        "Always explain tradeoffs",
        "Prefer simple solutions",
      ],
      instructions: "When reviewing code, check for race conditions first.",
    },
    ...overrides,
  };
}

function testSkills(): LoadedSkill[] {
  return [
    {
      name: "acme/code-review",
      version: "2.1.0",
      content: "# Code Review Skill\n\nReview code for correctness and security.\n",
      permissions: ["file:read"],
      tokens_estimate: 1500,
    },
    {
      name: "acme/testing",
      version: "1.0.0",
      content: "# Testing Skill\n\nWrite and run tests.\n",
      permissions: [],
      tokens_estimate: 800,
    },
  ];
}

// --- Export tests ---

describe("openclaw export", () => {
  it("creates SOUL.md with persona character instructions", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-basic");

    const result = await openclawTarget.export(persona, [], { outputDir });

    expect(result.files).toContain("SOUL.md");
    const soul = await fs.readFile(path.join(outputDir, "SOUL.md"), "utf-8");
    expect(soul).toContain("<!-- Generated by SPM from persona: test-agent@1.2.0 -->");
    expect(soul).toContain("## Persona");
    expect(soul).toContain("Senior backend engineer");
    expect(soul).toContain("**Tone:** direct, concise");
    expect(soul).toContain("- Always explain tradeoffs");
    expect(soul).toContain("- Prefer simple solutions");
    expect(soul).toContain("When reviewing code, check for race conditions first.");
  });

  it("creates AGENTS.md with skill listing", async () => {
    const persona = testPersona();
    const skills = testSkills();
    const outputDir = path.join(tmpDir, "export-skills");

    const result = await openclawTarget.export(persona, skills, { outputDir });

    expect(result.files).toContain("AGENTS.md");
    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("<!-- Generated by SPM from persona: test-agent@1.2.0 -->");
    expect(agents).toContain("## Skills");
    expect(agents).toContain("- **acme/code-review** (v2.1.0) — 1500 tokens");
    expect(agents).toContain("- **acme/testing** (v1.0.0) — 800 tokens");
    expect(agents).toContain("skills/acme/code-review/SKILL.md");
    expect(agents).toContain('skill_load("skill-name")');
    expect(agents).toContain('skill_search("query")');
  });

  it("exports skill files into skills/ directory", async () => {
    const persona = testPersona();
    const skills = testSkills();
    const outputDir = path.join(tmpDir, "export-skill-files");

    const result = await openclawTarget.export(persona, skills, { outputDir });

    // SKILL.md files exported
    expect(result.files).toContain("skills/acme/code-review/SKILL.md");
    expect(result.files).toContain("skills/acme/testing/SKILL.md");
    expect(result.files).toContain("skills/acme/code-review/skill.json");
    expect(result.files).toContain("skills/acme/testing/skill.json");

    // Verify content
    const reviewContent = await fs.readFile(
      path.join(outputDir, "skills", "acme/code-review", "SKILL.md"),
      "utf-8",
    );
    expect(reviewContent).toContain("Review code for correctness and security");

    const testContent = await fs.readFile(
      path.join(outputDir, "skills", "acme/testing", "SKILL.md"),
      "utf-8",
    );
    expect(testContent).toContain("Write and run tests");

    // Verify metadata
    const meta = JSON.parse(
      await fs.readFile(
        path.join(outputDir, "skills", "acme/code-review", "skill.json"),
        "utf-8",
      ),
    );
    expect(meta.name).toBe("acme/code-review");
    expect(meta.version).toBe("2.1.0");
    expect(meta.tokens_estimate).toBe(1500);
    expect(meta.permissions).toEqual(["file:read"]);
  });

  it("creates AGENTS.md without skills section when no skills", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-no-skills");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).not.toContain("### Exported skills:");
    expect(agents).toContain("No skills exported");
  });

  it("creates config/mcporter.json", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-mcporter");

    const result = await openclawTarget.export(persona, [], { outputDir });

    expect(result.files).toContain("config/mcporter.json");
    const raw = await fs.readFile(path.join(outputDir, "config", "mcporter.json"), "utf-8");
    const config = JSON.parse(raw);
    expect(config.mcpServers.spm).toBeDefined();
    expect(config.mcpServers.spm.command).toBeDefined();
    expect(config.mcpServers.spm.args).toContain("serve");
  });

  it("creates skills/ directory", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-dirs");

    await openclawTarget.export(persona, [], { outputDir });

    const stat = await fs.stat(path.join(outputDir, "skills"));
    expect(stat.isDirectory()).toBe(true);
  });

  it("does not overwrite existing mcporter.json", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-preserve");
    const mcporterDir = path.join(outputDir, "config");
    await fs.mkdir(mcporterDir, { recursive: true });
    await fs.writeFile(
      path.join(mcporterDir, "mcporter.json"),
      '{"mcpServers":{"custom":{"command":"custom"}}}',
    );

    const result = await openclawTarget.export(persona, [], { outputDir, overwrite: true });

    expect(result.files).not.toContain("config/mcporter.json");
    const raw = await fs.readFile(path.join(mcporterDir, "mcporter.json"), "utf-8");
    expect(raw).toContain('"custom"');
  });

  it("throws when output directory exists without --overwrite", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-exists");
    await fs.mkdir(outputDir, { recursive: true });

    await expect(
      openclawTarget.export(persona, [], { outputDir }),
    ).rejects.toThrow("Output directory already exists");
  });

  it("succeeds with overwrite flag on existing directory", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "export-overwrite");
    await fs.mkdir(outputDir, { recursive: true });

    const result = await openclawTarget.export(persona, [], { outputDir, overwrite: true });
    expect(result.files).toContain("SOUL.md");
  });
});

// --- Temperature → thinkingLevel mapping ---

describe("temperature to thinkingLevel mapping", () => {
  it("maps low temperature to high thinkingLevel", async () => {
    const persona = testPersona({ settings: { temperature: 0.2 } });
    const outputDir = path.join(tmpDir, "temp-high");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("**Recommended thinkingLevel:** high");
  });

  it("maps medium-low temperature to medium thinkingLevel", async () => {
    const persona = testPersona({ settings: { temperature: 0.4 } });
    const outputDir = path.join(tmpDir, "temp-medium");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("**Recommended thinkingLevel:** medium");
  });

  it("maps medium temperature to low thinkingLevel", async () => {
    const persona = testPersona({ settings: { temperature: 0.6 } });
    const outputDir = path.join(tmpDir, "temp-low");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("**Recommended thinkingLevel:** low");
  });

  it("maps high temperature to minimal thinkingLevel", async () => {
    const persona = testPersona({ settings: { temperature: 0.9 } });
    const outputDir = path.join(tmpDir, "temp-minimal");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("**Recommended thinkingLevel:** minimal");
  });

  it("omits thinkingLevel when no temperature set", async () => {
    const persona = testPersona();
    const outputDir = path.join(tmpDir, "temp-none");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).not.toContain("thinkingLevel");
  });

  it("maps boundary value 0.3 to high", async () => {
    const persona = testPersona({ settings: { temperature: 0.3 } });
    const outputDir = path.join(tmpDir, "temp-boundary-03");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("**Recommended thinkingLevel:** high");
  });

  it("maps boundary value 0.5 to medium", async () => {
    const persona = testPersona({ settings: { temperature: 0.5 } });
    const outputDir = path.join(tmpDir, "temp-boundary-05");

    await openclawTarget.export(persona, [], { outputDir });

    const agents = await fs.readFile(path.join(outputDir, "AGENTS.md"), "utf-8");
    expect(agents).toContain("**Recommended thinkingLevel:** medium");
  });
});

// --- Deploy tests ---

describe("openclaw deploy", () => {
  it("creates workspace and updates openclaw.json", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    const result = await openclawTarget.deploy(persona, [], {
      agentId: "my-agent",
      configPath,
      overwrite: true,
    });

    expect(result.agentId).toBe("my-agent");
    expect(result.configUpdated).toBe(true);
    expect(result.bindingAdded).toBe(false);

    // Workspace was created with SOUL.md
    const soul = await fs.readFile(path.join(result.workspaceDir, "SOUL.md"), "utf-8");
    expect(soul).toContain("test-agent@1.2.0");

    // openclaw.json was updated
    const config = JSON.parse(await fs.readFile(configPath, "utf-8"));
    expect(config.agents.list).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ id: "my-agent" }),
      ]),
    );
  });

  it("adds channel binding when --bind-channel specified", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    const result = await openclawTarget.deploy(persona, [], {
      agentId: "tg-agent",
      bindChannel: "telegram",
      configPath,
      overwrite: true,
    });

    expect(result.bindingAdded).toBe(true);

    const config = JSON.parse(await fs.readFile(configPath, "utf-8"));
    expect(config.bindings).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          agentId: "tg-agent",
          match: { channel: "telegram" },
        }),
      ]),
    );
  });

  it("adds binding with accountId", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    await openclawTarget.deploy(persona, [], {
      agentId: "wa-agent",
      bindChannel: "whatsapp",
      bindAccountId: "personal",
      configPath,
      overwrite: true,
    });

    const config = JSON.parse(await fs.readFile(configPath, "utf-8"));
    expect(config.bindings[0].match).toEqual({
      channel: "whatsapp",
      accountId: "personal",
    });
  });

  it("does not duplicate agent on re-deploy", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    await openclawTarget.deploy(persona, [], {
      agentId: "agent1",
      configPath,
      overwrite: true,
    });

    const result = await openclawTarget.deploy(persona, [], {
      agentId: "agent1",
      configPath,
      overwrite: true,
    });

    expect(result.configUpdated).toBe(false);

    const config = JSON.parse(await fs.readFile(configPath, "utf-8"));
    const agentEntries = config.agents.list.filter(
      (a: { id: string }) => a.id === "agent1",
    );
    expect(agentEntries).toHaveLength(1);
  });

  it("does not duplicate binding on re-deploy", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    await openclawTarget.deploy(persona, [], {
      agentId: "agent1",
      bindChannel: "telegram",
      configPath,
      overwrite: true,
    });

    await openclawTarget.deploy(persona, [], {
      agentId: "agent1",
      bindChannel: "telegram",
      configPath,
      overwrite: true,
    });

    const config = JSON.parse(await fs.readFile(configPath, "utf-8"));
    const tgBindings = config.bindings.filter(
      (b: { agentId: string; match: { channel: string } }) =>
        b.agentId === "agent1" && b.match.channel === "telegram",
    );
    expect(tgBindings).toHaveLength(1);
  });

  it("preserves existing agents in openclaw.json", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    // Pre-populate with existing agent
    await fs.writeFile(
      configPath,
      JSON.stringify({
        agents: { list: [{ id: "existing", workspace: "/some/path" }] },
        bindings: [{ agentId: "existing", match: { channel: "slack" } }],
      }),
    );

    await openclawTarget.deploy(persona, [], {
      agentId: "new-agent",
      configPath,
      overwrite: true,
    });

    const config = JSON.parse(await fs.readFile(configPath, "utf-8"));
    expect(config.agents.list).toHaveLength(2);
    expect(config.agents.list[0].id).toBe("existing");
    expect(config.agents.list[1].id).toBe("new-agent");
    expect(config.bindings[0].match.channel).toBe("slack");
  });

  it("returns docker fragment", async () => {
    const persona = testPersona();
    const configPath = path.join(tmpDir, "openclaw.json");

    const result = await openclawTarget.deploy(persona, [], {
      agentId: "dock-agent",
      configPath,
      overwrite: true,
    });

    expect(result.dockerFragment).toContain("workspace-dock-agent");
    expect(result.dockerFragment).toContain("/home/node/.openclaw/workspace-dock-agent");
  });
});

// --- Import tests ---

describe("openclaw import", () => {
  it("imports SPM-generated workspace", async () => {
    const persona = testPersona();
    const skills = testSkills();
    const exportDir = path.join(tmpDir, "workspace-test-agent");

    // First export
    await openclawTarget.export(persona, skills, { outputDir: exportDir });

    // Then import
    const imported = await openclawTarget.import!(exportDir);

    expect(imported.name).toBe("test-agent");
    expect(imported.character.role).toBe(persona.character.role);
    expect(imported.character.tone).toBe("direct, concise");
    expect(imported.character.guidelines).toEqual([
      "Always explain tradeoffs",
      "Prefer simple solutions",
    ]);
    expect(imported.character.instructions).toContain("race conditions");
  });

  it("reads skill references from exported skills/ directory", async () => {
    const persona = testPersona();
    const skills = testSkills();
    const exportDir = path.join(tmpDir, "workspace-with-skills");

    await openclawTarget.export(persona, skills, { outputDir: exportDir });

    const imported = await openclawTarget.import!(exportDir);

    expect(imported.skills).toBeDefined();
    expect(imported.skills!["acme/code-review"]).toBe("^2.1.0");
    expect(imported.skills!["acme/testing"]).toBe("^1.0.0");
  });

  it("falls back to AGENTS.md parsing when no skills/ directory", async () => {
    const workspaceDir = path.join(tmpDir, "workspace-agents-only");
    await fs.mkdir(workspaceDir, { recursive: true });
    await fs.writeFile(
      path.join(workspaceDir, "SOUL.md"),
      "## Persona\n\nA helper.\n",
    );
    await fs.writeFile(
      path.join(workspaceDir, "AGENTS.md"),
      "## Skills\n\n- **acme/lint** (v3.0.0) — 500 tokens\n",
    );

    const imported = await openclawTarget.import!(workspaceDir);

    expect(imported.skills).toBeDefined();
    expect(imported.skills!["acme/lint"]).toBe("^3.0.0");
  });

  it("handles workspace without AGENTS.md or skills/", async () => {
    const workspaceDir = path.join(tmpDir, "workspace-minimal");
    await fs.mkdir(workspaceDir, { recursive: true });
    await fs.writeFile(
      path.join(workspaceDir, "SOUL.md"),
      "## Persona\n\nA helpful assistant.\n\n**Tone:** friendly\n",
    );

    const imported = await openclawTarget.import!(workspaceDir);

    expect(imported.character.role).toBe("A helpful assistant.");
    expect(imported.character.tone).toBe("friendly");
    expect(imported.skills).toBeUndefined();
  });

  it("extracts name from directory when no metadata comment", async () => {
    const workspaceDir = path.join(tmpDir, "workspace-my-bot");
    await fs.mkdir(workspaceDir, { recursive: true });
    await fs.writeFile(
      path.join(workspaceDir, "SOUL.md"),
      "## Persona\n\nA bot.\n",
    );

    const imported = await openclawTarget.import!(workspaceDir);
    expect(imported.name).toBe("my-bot");
  });

  it("throws when SOUL.md is missing", async () => {
    const workspaceDir = path.join(tmpDir, "workspace-empty");
    await fs.mkdir(workspaceDir, { recursive: true });

    await expect(openclawTarget.import!(workspaceDir)).rejects.toThrow(
      "SOUL.md not found",
    );
  });

  it("skips style note during import (derived from settings)", async () => {
    const workspaceDir = path.join(tmpDir, "workspace-style-note");
    await fs.mkdir(workspaceDir, { recursive: true });
    await fs.writeFile(
      path.join(workspaceDir, "SOUL.md"),
      [
        "## Persona",
        "",
        "A precise analyst.",
        "",
        "**Tone:** formal",
        "",
        "**Style note:** Be precise, factual, and conservative in your responses.",
        "",
      ].join("\n"),
    );

    const imported = await openclawTarget.import!(workspaceDir);
    expect(imported.character.role).toBe("A precise analyst.");
    expect(imported.character.tone).toBe("formal");
    // Style note should not appear in instructions
    expect(imported.character.instructions).toBeUndefined();
  });
});

// --- Export → Import roundtrip ---

describe("export → import roundtrip", () => {
  it("preserves character fields through roundtrip", async () => {
    const original = testPersona();
    const exportDir = path.join(tmpDir, "roundtrip");

    await openclawTarget.export(original, [], { outputDir: exportDir });
    const imported = await openclawTarget.import!(exportDir);

    expect(imported.character.role).toBe(original.character.role);
    expect(imported.character.tone).toBe(original.character.tone);
    expect(imported.character.guidelines).toEqual(original.character.guidelines);
    expect(imported.character.instructions).toBe(original.character.instructions);
  });

  it("preserves character with minimal fields", async () => {
    const original = testPersona({
      character: {
        role: "A simple helper.",
      },
    });
    const exportDir = path.join(tmpDir, "roundtrip-minimal");

    await openclawTarget.export(original, [], { outputDir: exportDir });
    const imported = await openclawTarget.import!(exportDir);

    expect(imported.character.role).toBe("A simple helper.");
    expect(imported.character.tone).toBeUndefined();
    expect(imported.character.guidelines).toBeUndefined();
  });

  it("preserves persona name through roundtrip", async () => {
    const original = testPersona({ name: "my-custom-agent" });
    const exportDir = path.join(tmpDir, "roundtrip-name");

    await openclawTarget.export(original, [], { outputDir: exportDir });
    const imported = await openclawTarget.import!(exportDir);

    expect(imported.name).toBe("my-custom-agent");
  });
});

// --- Client registry ---

describe("openclaw client registration", () => {
  it("openclaw client is registered with alias", async () => {
    const { getClient, getAllClientKeys } = await import("../src/clients/index.js");

    const client = getClient("openclaw");
    expect(client).toBeDefined();
    expect(client!.name).toBe("OpenClaw");

    const byAlias = getClient("oc");
    expect(byAlias).toBeDefined();
    expect(byAlias!.id).toBe("openclaw");

    const keys = getAllClientKeys();
    expect(keys).toContain("openclaw");
    expect(keys).toContain("oc");
  });

  it("openclaw config points to mcporter.json", async () => {
    const { getClient } = await import("../src/clients/index.js");
    const client = getClient("openclaw")!;

    expect(client.configPath).toContain(".openclaw");
    expect(client.configPath).toContain("mcporter.json");
    expect(client.jsonPath).toEqual(["mcpServers", "spm"]);
  });
});

// --- Target registry ---

describe("target registry", () => {
  it("openclaw target is registered", async () => {
    const { getTarget, getAllTargets, getAllTargetIds } = await import("../src/targets/index.js");

    expect(getTarget("openclaw")).toBeDefined();
    expect(getTarget("openclaw")!.name).toBe("OpenClaw");
    expect(getTarget("unknown")).toBeUndefined();
    expect(getAllTargets()).toHaveLength(1);
    expect(getAllTargetIds()).toEqual(["openclaw"]);
  });
});
