import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { realpathSync } from "node:fs";
import { parse as parseJsonc } from "jsonc-parser";
import { buildCharacterInstructions } from "../core/persona.js";
import type { ParsedSoul, LegacyPersonaManifest, LoadedSkill, PersonaCharacter } from "../types/index.js";
import type {
  DeployTarget,
  ExportOptions,
  ExportResult,
  DeployOptions,
  DeployResult,
  RemoteDeployOptions,
  RemoteDeployResult,
} from "./types.js";
import { getDefaultConnection, getConnection } from "../core/connections.js";

// -- Helpers --

function getSkillsBin(): string {
  const arg1 = process.argv[1];
  if (arg1) {
    try {
      return realpathSync(arg1);
    } catch {
      return arg1;
    }
  }
  return "spm";
}

function mapTemperatureToThinkingLevel(
  temperature: number | undefined,
): string | null {
  if (temperature === undefined) return null;
  if (temperature <= 0.3) return "high";
  if (temperature <= 0.5) return "medium";
  if (temperature <= 0.7) return "low";
  return "minimal";
}

function generateSoulMd(soul: ParsedSoul): string {
  const header = `<!-- Generated by SPM from persona: ${soul.frontmatter.name}@${soul.frontmatter.version} -->\n\n`;
  const body = buildCharacterInstructions(soul);
  return header + body + "\n";
}

function generateAgentsMd(
  soul: ParsedSoul,
  skills: LoadedSkill[],
): string {
  const lines: string[] = [];
  const { frontmatter } = soul;

  lines.push(
    `<!-- Generated by SPM from persona: ${frontmatter.name}@${frontmatter.version} -->`,
  );
  lines.push("");
  lines.push("## Skills");
  lines.push("");

  if (skills.length > 0) {
    lines.push(
      "This agent uses skills managed by SPM (Skillbase Package Manager).",
    );
    lines.push(
      "Skill instructions are exported in the `skills/` directory and also available dynamically via the `spm` MCP server.",
    );
    lines.push("");

    lines.push("### Exported skills:");
    for (const s of skills) {
      lines.push(`- **${s.name}** (v${s.version}) — ${s.tokens_estimate} tokens → \`skills/${s.name}/SKILL.md\``);
    }
    lines.push("");
  } else {
    lines.push("No skills exported with this persona.");
    lines.push("");
  }

  lines.push("### Dynamic loading via MCP:");
  lines.push(
    'Use `skill_load("skill-name")` to load a skill\'s instructions into context.',
  );
  lines.push('Use `skill_search("query")` to find additional skills.');

  const temperature = frontmatter.skillbase?.settings?.temperature;
  const thinkingLevel = mapTemperatureToThinkingLevel(temperature);
  if (thinkingLevel) {
    lines.push("");
    lines.push(
      `> **Recommended thinkingLevel:** ${thinkingLevel} (based on persona temperature ${temperature})`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

function generateMcporterJson(): string {
  const config = {
    mcpServers: {
      spm: {
        command: process.execPath,
        args: [getSkillsBin(), "serve"],
      },
    },
  };
  return JSON.stringify(config, null, 2) + "\n";
}

async function findSkillJsonFiles(dir: string): Promise<string[]> {
  const results: string[] = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await findSkillJsonFiles(fullPath)));
    } else if (entry.name === "skill.json") {
      results.push(fullPath);
    }
  }
  return results;
}

// -- Export --

async function exportPersona(
  soul: ParsedSoul,
  skills: LoadedSkill[],
  options: ExportOptions,
): Promise<ExportResult> {
  const { outputDir, overwrite } = options;
  const files: string[] = [];

  // Check existing directory
  try {
    await fs.access(outputDir);
    if (!overwrite) {
      throw new Error(
        `Output directory already exists: ${outputDir}\nUse --overwrite to replace.`,
      );
    }
  } catch (err) {
    if (err instanceof Error && err.message.startsWith("Output directory")) {
      throw err;
    }
  }

  await fs.mkdir(outputDir, { recursive: true });
  await fs.mkdir(path.join(outputDir, "skills"), { recursive: true });
  await fs.mkdir(path.join(outputDir, "config"), { recursive: true });

  // SOUL.md
  const soulPath = path.join(outputDir, "SOUL.md");
  await fs.writeFile(soulPath, generateSoulMd(soul), "utf-8");
  files.push("SOUL.md");

  // AGENTS.md
  const agentsPath = path.join(outputDir, "AGENTS.md");
  await fs.writeFile(agentsPath, generateAgentsMd(soul, skills), "utf-8");
  files.push("AGENTS.md");

  // Export skill files
  for (const skill of skills) {
    const skillDir = path.join(outputDir, "skills", skill.name);
    await fs.mkdir(skillDir, { recursive: true });
    await fs.writeFile(
      path.join(skillDir, "SKILL.md"),
      skill.content,
      "utf-8",
    );
    files.push(`skills/${skill.name}/SKILL.md`);

    const meta = {
      name: skill.name,
      version: skill.version,
      tokens_estimate: skill.tokens_estimate,
      permissions: skill.permissions,
      works_with: skill.works_with,
    };
    await fs.writeFile(
      path.join(skillDir, "skill.json"),
      JSON.stringify(meta, null, 2) + "\n",
      "utf-8",
    );
    files.push(`skills/${skill.name}/skill.json`);
  }

  // config/mcporter.json
  const mcporterPath = path.join(outputDir, "config", "mcporter.json");
  try {
    await fs.access(mcporterPath);
  } catch {
    await fs.writeFile(mcporterPath, generateMcporterJson(), "utf-8");
    files.push("config/mcporter.json");
  }

  return { outputDir, files };
}

// -- Deploy --

async function deployPersona(
  soul: ParsedSoul,
  skills: LoadedSkill[],
  options: DeployOptions,
): Promise<DeployResult> {
  const { agentId, bindChannel, bindAccountId, overwrite } = options;
  const configPath =
    options.configPath ??
    path.join(os.homedir(), ".openclaw", "openclaw.json");

  const workspaceDir = path.join(
    os.homedir(),
    ".openclaw",
    `workspace-${agentId}`,
  );

  await exportPersona(soul, skills, {
    outputDir: workspaceDir,
    overwrite,
  });

  let configUpdated = false;
  let bindingAdded = false;

  try {
    let raw: string;
    try {
      raw = await fs.readFile(configPath, "utf-8");
    } catch {
      raw = "{}";
    }

    const config = parseJsonc(raw) as Record<string, unknown>;

    if (!config.agents || typeof config.agents !== "object") {
      config.agents = { list: [] };
    }
    const agents = config.agents as { list: Array<{ id: string; workspace: string }> };
    if (!Array.isArray(agents.list)) {
      agents.list = [];
    }

    const existing = agents.list.find((a) => a.id === agentId);
    if (!existing) {
      agents.list.push({ id: agentId, workspace: workspaceDir });
      configUpdated = true;
    } else if (existing.workspace !== workspaceDir) {
      existing.workspace = workspaceDir;
      configUpdated = true;
    }

    if (bindChannel) {
      if (!Array.isArray(config.bindings)) {
        config.bindings = [];
      }
      const bindings = config.bindings as Array<{
        agentId: string;
        match: { channel: string; accountId?: string };
      }>;

      const matchExists = bindings.some(
        (b) =>
          b.agentId === agentId &&
          b.match.channel === bindChannel &&
          (bindAccountId ? b.match.accountId === bindAccountId : true),
      );

      if (!matchExists) {
        const match: { channel: string; accountId?: string } = {
          channel: bindChannel,
        };
        if (bindAccountId) match.accountId = bindAccountId;
        bindings.push({ agentId, match });
        bindingAdded = true;
        configUpdated = true;
      }
    }

    if (configUpdated) {
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(
        configPath,
        JSON.stringify(config, null, 2) + "\n",
        "utf-8",
      );
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to update openclaw.json: ${message}`);
  }

  const dockerFragment = [
    "# Add to docker-compose.extra.yml volumes:",
    `- ~/.openclaw/workspace-${agentId}:/home/node/.openclaw/workspace-${agentId}`,
  ].join("\n");

  return {
    agentId,
    workspaceDir,
    configUpdated,
    bindingAdded,
    dockerFragment,
  };
}

// -- Import --

async function importPersona(sourcePath: string): Promise<LegacyPersonaManifest> {
  const soulPath = path.join(sourcePath, "SOUL.md");
  let soulContent: string;

  try {
    soulContent = await fs.readFile(soulPath, "utf-8");
  } catch {
    throw new Error(`SOUL.md not found in ${sourcePath}`);
  }

  let name = path.basename(sourcePath).replace(/^workspace-/, "");
  const metaMatch = soulContent.match(
    /<!-- Generated by SPM from persona: ([^@]+)@/,
  );
  if (metaMatch) {
    name = metaMatch[1];
  }

  const character = parseSoulMd(soulContent);
  const skills: Record<string, string> = {};
  const skillsDir = path.join(sourcePath, "skills");
  let foundSkillFiles = false;

  try {
    await fs.access(skillsDir);
    const skillJsonPaths = await findSkillJsonFiles(skillsDir);
    for (const jsonPath of skillJsonPaths) {
      try {
        const metaRaw = await fs.readFile(jsonPath, "utf-8");
        const meta = JSON.parse(metaRaw) as { name: string; version: string };
        skills[meta.name] = `^${meta.version}`;
        foundSkillFiles = true;
      } catch { /* skip */ }
    }
  } catch { /* no skills dir */ }

  if (!foundSkillFiles) {
    try {
      const agentsContent = await fs.readFile(
        path.join(sourcePath, "AGENTS.md"),
        "utf-8",
      );
      const skillMatches = agentsContent.matchAll(
        /- \*\*([^*]+)\*\* \(v([^)]+)\)/g,
      );
      for (const match of skillMatches) {
        skills[match[1]] = `^${match[2]}`;
      }
    } catch { /* skip */ }
  }

  return {
    schema_version: 1,
    name,
    version: "1.0.0",
    description: `Imported from OpenClaw workspace: ${name}`,
    author: "imported",
    license: "MIT",
    skills: Object.keys(skills).length > 0 ? skills : undefined,
    character,
  };
}

function parseSoulMd(content: string): PersonaCharacter {
  const cleaned = content.replace(/<!--[\s\S]*?-->\s*/g, "").trim();

  const lines = cleaned.split("\n");
  let role = "";
  let tone: string | undefined;
  const guidelines: string[] = [];
  const instructionParts: string[] = [];
  let section: "role" | "guidelines" | "instructions" | "none" = "none";

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed === "## Persona") {
      section = "role";
      continue;
    }

    if (trimmed.startsWith("**Tone:**")) {
      tone = trimmed.replace("**Tone:**", "").trim();
      section = "none";
      continue;
    }

    if (trimmed === "**Guidelines:**") {
      section = "guidelines";
      continue;
    }

    if (trimmed.startsWith("**Style note:**")) {
      continue;
    }

    if (section === "role" && trimmed) {
      role = trimmed;
      section = "none";
      continue;
    }

    if (section === "guidelines") {
      if (trimmed.startsWith("- ")) {
        guidelines.push(trimmed.slice(2));
      } else if (trimmed) {
        section = "instructions";
        instructionParts.push(trimmed);
      }
      continue;
    }

    if (section === "instructions" || (section === "none" && trimmed && role)) {
      if (trimmed) {
        instructionParts.push(trimmed);
        section = "instructions";
      }
    }
  }

  return {
    role: role || "AI assistant",
    tone,
    guidelines: guidelines.length > 0 ? guidelines : undefined,
    instructions:
      instructionParts.length > 0 ? instructionParts.join("\n") : undefined,
  };
}

// -- Remote deploy --

async function remoteDeployPersona(
  soul: ParsedSoul,
  skills: LoadedSkill[],
  options: RemoteDeployOptions,
): Promise<RemoteDeployResult> {
  const resolved = options.connectionName
    ? await getConnection(options.connectionName)
    : await getDefaultConnection();

  if (!resolved) {
    throw new Error(
      options.connectionName
        ? `Connection "${options.connectionName}" not found`
        : "No remote connections configured. Add one with: spm connect openclaw --remote <url>",
    );
  }

  const connName = "name" in resolved ? (resolved as { name: string }).name : options.connectionName!;
  const conn = "connection" in resolved ? (resolved as { connection: { url: string } }).connection : resolved;
  const token = "resolvedToken" in resolved ? (resolved as { resolvedToken?: string }).resolvedToken : undefined;

  const soulMd = generateSoulMd(soul);
  const skillPayloads = skills.map((s) => ({
    name: s.name,
    version: s.version,
    content: s.content,
  }));

  const response = await fetch(`${conn.url}/api/v1/skills/install`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: JSON.stringify({
      soul_md: soulMd,
      skills: skillPayloads,
      persona: {
        name: soul.frontmatter.name,
        version: soul.frontmatter.version,
      },
    }),
    signal: AbortSignal.timeout(30_000),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => "");
    throw new Error(`Remote deploy failed (${response.status}): ${errorText}`);
  }

  return {
    connectionName: connName,
    url: conn.url,
    success: true,
    message: `Persona "${soul.frontmatter.name}" deployed to ${connName}`,
  };
}

// -- Target definition --

export const openclawTarget: DeployTarget = {
  id: "openclaw",
  name: "OpenClaw",
  export: exportPersona,
  deploy: deployPersona,
  import: importPersona,
  remoteDeploy: remoteDeployPersona,
};
