import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { realpathSync } from "node:fs";
import { parse as parseJsonc } from "jsonc-parser";
import { buildCharacterInstructions } from "../core/persona.js";
import type { PersonaManifest, LoadedSkill, PersonaCharacter } from "../types/index.js";
import type {
  DeployTarget,
  ExportOptions,
  ExportResult,
  DeployOptions,
  DeployResult,
} from "./types.js";

// -- Helpers --

function getSkillsBin(): string {
  const arg1 = process.argv[1];
  if (arg1) {
    try {
      return realpathSync(arg1);
    } catch {
      return arg1;
    }
  }
  return "spm";
}

function mapTemperatureToThinkingLevel(
  temperature: number | undefined,
): string | null {
  if (temperature === undefined) return null;
  if (temperature <= 0.3) return "high";
  if (temperature <= 0.5) return "medium";
  if (temperature <= 0.7) return "low";
  return "minimal";
}

function generateSoulMd(persona: PersonaManifest): string {
  const header = `<!-- Generated by SPM from persona: ${persona.name}@${persona.version} -->\n\n`;
  const body = buildCharacterInstructions(persona.character, persona.settings);
  return header + body + "\n";
}

function generateAgentsMd(
  persona: PersonaManifest,
  skills: LoadedSkill[],
): string {
  const lines: string[] = [];

  lines.push(
    `<!-- Generated by SPM from persona: ${persona.name}@${persona.version} -->`,
  );
  lines.push("");
  lines.push("## Skills");
  lines.push("");

  if (skills.length > 0) {
    lines.push(
      "This agent uses skills managed by SPM (Skillbase Package Manager).",
    );
    lines.push(
      "Skill instructions are exported in the `skills/` directory and also available dynamically via the `spm` MCP server.",
    );
    lines.push("");

    lines.push("### Exported skills:");
    for (const s of skills) {
      lines.push(`- **${s.name}** (v${s.version}) — ${s.tokens_estimate} tokens → \`skills/${s.name}/SKILL.md\``);
    }
    lines.push("");
  } else {
    lines.push("No skills exported with this persona.");
    lines.push("");
  }

  lines.push("### Dynamic loading via MCP:");
  lines.push(
    'Use `skill_load("skill-name")` to load a skill\'s instructions into context.',
  );
  lines.push('Use `skill_search("query")` to find additional skills.');

  const thinkingLevel = mapTemperatureToThinkingLevel(
    persona.settings?.temperature,
  );
  if (thinkingLevel) {
    lines.push("");
    lines.push(
      `> **Recommended thinkingLevel:** ${thinkingLevel} (based on persona temperature ${persona.settings!.temperature})`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

function generateMcporterJson(): string {
  const config = {
    mcpServers: {
      spm: {
        command: process.execPath,
        args: [getSkillsBin(), "serve"],
      },
    },
  };
  return JSON.stringify(config, null, 2) + "\n";
}

async function findSkillJsonFiles(dir: string): Promise<string[]> {
  const results: string[] = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await findSkillJsonFiles(fullPath)));
    } else if (entry.name === "skill.json") {
      results.push(fullPath);
    }
  }
  return results;
}

// -- Export --

async function exportPersona(
  persona: PersonaManifest,
  skills: LoadedSkill[],
  options: ExportOptions,
): Promise<ExportResult> {
  const { outputDir, overwrite } = options;
  const files: string[] = [];

  // Check existing directory
  try {
    await fs.access(outputDir);
    if (!overwrite) {
      throw new Error(
        `Output directory already exists: ${outputDir}\nUse --overwrite to replace.`,
      );
    }
  } catch (err) {
    if (err instanceof Error && err.message.startsWith("Output directory")) {
      throw err;
    }
    // Directory doesn't exist — good
  }

  // Create directory structure
  await fs.mkdir(outputDir, { recursive: true });
  await fs.mkdir(path.join(outputDir, "skills"), { recursive: true });
  await fs.mkdir(path.join(outputDir, "config"), { recursive: true });

  // SOUL.md
  const soulPath = path.join(outputDir, "SOUL.md");
  await fs.writeFile(soulPath, generateSoulMd(persona), "utf-8");
  files.push("SOUL.md");

  // AGENTS.md
  const agentsPath = path.join(outputDir, "AGENTS.md");
  await fs.writeFile(agentsPath, generateAgentsMd(persona, skills), "utf-8");
  files.push("AGENTS.md");

  // Export skill files into skills/{name}/
  for (const skill of skills) {
    const skillDir = path.join(outputDir, "skills", skill.name);
    await fs.mkdir(skillDir, { recursive: true });

    // Write SKILL.md with full content
    await fs.writeFile(
      path.join(skillDir, "SKILL.md"),
      skill.content,
      "utf-8",
    );
    files.push(`skills/${skill.name}/SKILL.md`);

    // Write skill metadata
    const meta = {
      name: skill.name,
      version: skill.version,
      tokens_estimate: skill.tokens_estimate,
      permissions: skill.permissions,
      works_with: skill.works_with,
    };
    await fs.writeFile(
      path.join(skillDir, "skill.json"),
      JSON.stringify(meta, null, 2) + "\n",
      "utf-8",
    );
    files.push(`skills/${skill.name}/skill.json`);
  }

  // config/mcporter.json
  const mcporterPath = path.join(outputDir, "config", "mcporter.json");
  try {
    await fs.access(mcporterPath);
    // Already exists, don't overwrite MCP config
  } catch {
    await fs.writeFile(mcporterPath, generateMcporterJson(), "utf-8");
    files.push("config/mcporter.json");
  }

  return { outputDir, files };
}

// -- Deploy --

async function deployPersona(
  persona: PersonaManifest,
  skills: LoadedSkill[],
  options: DeployOptions,
): Promise<DeployResult> {
  const { agentId, bindChannel, bindAccountId, overwrite } = options;
  const configPath =
    options.configPath ??
    path.join(os.homedir(), ".openclaw", "openclaw.json");

  // 1. Create workspace directory
  const workspaceDir = path.join(
    os.homedir(),
    ".openclaw",
    `workspace-${agentId}`,
  );

  // 2. Run export into workspace
  await exportPersona(persona, skills, {
    outputDir: workspaceDir,
    overwrite,
  });

  // 3. Update openclaw.json
  let configUpdated = false;
  let bindingAdded = false;

  try {
    let raw: string;
    try {
      raw = await fs.readFile(configPath, "utf-8");
    } catch {
      raw = "{}";
    }

    const config = parseJsonc(raw) as Record<string, unknown>;

    // Ensure agents.list exists
    if (!config.agents || typeof config.agents !== "object") {
      config.agents = { list: [] };
    }
    const agents = config.agents as { list: Array<{ id: string; workspace: string }> };
    if (!Array.isArray(agents.list)) {
      agents.list = [];
    }

    // Add agent if not already present
    const existing = agents.list.find((a) => a.id === agentId);
    if (!existing) {
      agents.list.push({ id: agentId, workspace: workspaceDir });
      configUpdated = true;
    } else if (existing.workspace !== workspaceDir) {
      existing.workspace = workspaceDir;
      configUpdated = true;
    }

    // Add binding if requested
    if (bindChannel) {
      if (!Array.isArray(config.bindings)) {
        config.bindings = [];
      }
      const bindings = config.bindings as Array<{
        agentId: string;
        match: { channel: string; accountId?: string };
      }>;

      const matchExists = bindings.some(
        (b) =>
          b.agentId === agentId &&
          b.match.channel === bindChannel &&
          (bindAccountId ? b.match.accountId === bindAccountId : true),
      );

      if (!matchExists) {
        const match: { channel: string; accountId?: string } = {
          channel: bindChannel,
        };
        if (bindAccountId) match.accountId = bindAccountId;
        bindings.push({ agentId, match });
        bindingAdded = true;
        configUpdated = true;
      }
    }

    if (configUpdated) {
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(
        configPath,
        JSON.stringify(config, null, 2) + "\n",
        "utf-8",
      );
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to update openclaw.json: ${message}`);
  }

  // 4. Generate Docker fragment
  const dockerFragment = [
    "# Add to docker-compose.extra.yml volumes:",
    `- ~/.openclaw/workspace-${agentId}:/home/node/.openclaw/workspace-${agentId}`,
  ].join("\n");

  return {
    agentId,
    workspaceDir,
    configUpdated,
    bindingAdded,
    dockerFragment,
  };
}

// -- Import --

async function importPersona(sourcePath: string): Promise<PersonaManifest> {
  const soulPath = path.join(sourcePath, "SOUL.md");
  let soulContent: string;

  try {
    soulContent = await fs.readFile(soulPath, "utf-8");
  } catch {
    throw new Error(`SOUL.md not found in ${sourcePath}`);
  }

  // Extract persona name from metadata comment or directory name
  let name = path.basename(sourcePath).replace(/^workspace-/, "");
  const metaMatch = soulContent.match(
    /<!-- Generated by SPM from persona: ([^@]+)@/,
  );
  if (metaMatch) {
    name = metaMatch[1];
  }

  // Parse SOUL.md into character fields
  const character = parseSoulMd(soulContent);

  // Check skills/ directory first, then fall back to AGENTS.md
  const skills: Record<string, string> = {};
  const skillsDir = path.join(sourcePath, "skills");
  let foundSkillFiles = false;

  try {
    await fs.access(skillsDir);
    // Recursively find all skill.json files under skills/
    const skillJsonPaths = await findSkillJsonFiles(skillsDir);
    for (const jsonPath of skillJsonPaths) {
      try {
        const metaRaw = await fs.readFile(jsonPath, "utf-8");
        const meta = JSON.parse(metaRaw) as { name: string; version: string };
        skills[meta.name] = `^${meta.version}`;
        foundSkillFiles = true;
      } catch {
        // Invalid skill.json — skip
      }
    }
  } catch {
    // No skills directory
  }

  if (!foundSkillFiles) {
    // Fall back to AGENTS.md parsing
    try {
      const agentsContent = await fs.readFile(
        path.join(sourcePath, "AGENTS.md"),
        "utf-8",
      );
      const skillMatches = agentsContent.matchAll(
        /- \*\*([^*]+)\*\* \(v([^)]+)\)/g,
      );
      for (const match of skillMatches) {
        skills[match[1]] = `^${match[2]}`;
      }
    } catch {
      // No AGENTS.md or no skill references
    }
  }

  return {
    schema_version: 1,
    name,
    version: "1.0.0",
    description: `Imported from OpenClaw workspace: ${name}`,
    author: "imported",
    license: "MIT",
    skills: Object.keys(skills).length > 0 ? skills : undefined,
    character,
  };
}

function parseSoulMd(content: string): PersonaCharacter {
  // Strip metadata comment
  const cleaned = content.replace(/<!--[\s\S]*?-->\s*/g, "").trim();

  const lines = cleaned.split("\n");
  let role = "";
  let tone: string | undefined;
  const guidelines: string[] = [];
  const instructionParts: string[] = [];
  let section: "role" | "guidelines" | "instructions" | "none" = "none";

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip persona header
    if (trimmed === "## Persona") {
      section = "role";
      continue;
    }

    // Detect tone
    if (trimmed.startsWith("**Tone:**")) {
      tone = trimmed.replace("**Tone:**", "").trim();
      section = "none";
      continue;
    }

    // Detect guidelines section
    if (trimmed === "**Guidelines:**") {
      section = "guidelines";
      continue;
    }

    // Detect style note (skip it — it's derived from settings)
    if (trimmed.startsWith("**Style note:**")) {
      continue;
    }

    // Collect based on current section
    if (section === "role" && trimmed) {
      role = trimmed;
      section = "none";
      continue;
    }

    if (section === "guidelines") {
      if (trimmed.startsWith("- ")) {
        guidelines.push(trimmed.slice(2));
      } else if (trimmed) {
        // End of guidelines, this is instructions
        section = "instructions";
        instructionParts.push(trimmed);
      }
      continue;
    }

    if (section === "instructions" || (section === "none" && trimmed && role)) {
      if (trimmed) {
        instructionParts.push(trimmed);
        section = "instructions";
      }
    }
  }

  return {
    role: role || "AI assistant",
    tone,
    guidelines: guidelines.length > 0 ? guidelines : undefined,
    instructions:
      instructionParts.length > 0 ? instructionParts.join("\n") : undefined,
  };
}

// -- Target definition --

export const openclawTarget: DeployTarget = {
  id: "openclaw",
  name: "OpenClaw",
  export: exportPersona,
  deploy: deployPersona,
  import: importPersona,
};
